################################################################################
MLI_FILE		= galen_framework.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= ocaml-galen-framework
################################################################################
